### ISSUE TITLE
Where can i get PP3380-AB PCIe card ?

### ISSUE THREAD

**Issue by Zibux** [ufrisk/pcileech#21] opened 2017-07-10 18:47 UTC
I cant found anywhere this card. Any help? In all shops it shows out of stock.

**Comment by Zibux** [comment] 2017-07-10 19:26
I found it will this work http://www.bplus.com.tw/adapter/PP3380-AB.html ?

**Comment by ufrisk** [comment] 2017-07-11 09:42
yes, thats the one, and I think they have it in stock.

**Comment by Zibux** [comment] 2017-07-13 11:37
I asked them question with email 3 days no answer. Is bplus still active ?

**Comment by ufrisk** [comment] 2017-07-13 16:17
yeah, they are active, I know others had problems that they are only replying on some email addresses tho.

you have DMA access over PCIe, nothing is preventing you for running PCILeech on the very same computer that you are targeting, just connect the USB-cable to the same computer...

**Comment by Zibux** [comment] 2017-07-15 16:18
So i have this setup http://prntscr.com/fw22r0 but dont have usb3 on my laptop will i need to buy adapter? 
If yes then any suggestions witch one to buy ?

**Comment by ufrisk** [comment] 2017-07-15 18:08
USB2 (on the attacker computer) will work fine too, it will be slower though.

**Comment by Zibux** [comment] 2017-07-21 15:47
So i bough PP3380 card i have some questions about flashing.
What you mean with
> NB! If flashing the PP3380 PCIe card the J3 jumper must be bridged to
connect the EEPROM.
When driver is loaded i should just insert the usb cable into usb2/usb3 port and something should happen ?

**Comment by ufrisk** [comment] 2017-07-22 01:27
You have to connect the two pins marked as J3 on the board with a jumper before flashing the board. The J3 pins must always be connected, even after flashing is completed.

https://en.wikipedia.org/wiki/Jumper_(computing)

When flashing (installing the driver) the card must be inserted in a PCIe slot.

If flashing is successful the card must be power cycled for the changes to take effect (reboot computer). After successful flash you should be able to connect the USB cable and start using the hw as a pcileech device.

**Comment by maxkunes** [comment] 2017-07-22 07:19
I recently purchased one on the bplus website to find a cheaper one in the US with garenteed faster shipping. 

Seems to be a distributor.

http://www.mfactors.com/pp3380-ab-usb3380-ab-evaluation-board/

**Comment by ufrisk** [comment] 2017-07-22 10:39
yes, mfactors is a distributor as well.

the firmware is explained in my defcon pdf presentation (slide 9) https://github.com/ufrisk/presentations/blob/master/DEFCON-24-Ulf-Frisk-Direct-Memory-Attack-the-Kernel-Final.pdf

unfortunately it's highly specific to the USB3380 chip and won't be adapted to another (non usb3380) board.

**Comment by Zibux** [comment] 2017-07-22 13:42
Can i connect these two pins just with wire http://prntscr.com/fyw2q2 because i dont have jumper atm?

**Comment by ufrisk** [comment] 2017-07-22 18:01
Yeah, I guess you can give it a try. Just be careful not to let the wire touch anything else - I fried one of my cards that way :/

**Comment by Zibux** [comment] 2017-07-23 20:47
Thank you so much ufirsk everything is working. You made my life.
The only problem is reading without driver i get to 3572 mb http://prntscr.com/fzc5gk any ideas why ?
Could it be possible to make dma to full memory only using hw without kernel driver ?

**Comment by ufrisk** [comment] 2017-07-23 21:16
Thanks for the update. I'm glad to see it's working for you =)

It's normal that the read fails around 3.5 GB, there is a "memory hole" in the physical address space there. Simply there is no memory there. That space is reserved for various memory mapped PCI-Express devices mostly.

The USB3380 will never be able to read addresses above 4GB without a kernel module unfortunately. The plan is to let PCILeech support other, more capable, FPGA based hardware in the future that will be able to achieve this. There is a risk it will take some time tho, and that the harware will be more expensive.

**Comment by omstation** [comment] 2017-07-23 23:05
Do you happen to have the schematic for the (PP3380-AB (USB3380-AB Evaluation Board), the links on the website are down but I would guess you have them.

**Comment by ufrisk** [comment] 2017-07-23 23:11
Even better, the Internet Archive have them. 

http://web.archive.org/web/20160621103932/http://bplus.com.tw/Adapter/PP3380-AB.html

**Comment by omstation** [comment] 2017-07-23 23:56
Thanks for that link, in response to what you were saying about > ~4gb, why is it necessary to use fpga based hardware? As speed doesn't seem to be the issue or from what I can tell, why is it necessary.

**Comment by ufrisk** [comment] 2017-07-24 00:02
The USB3380 chip does not support 64-bit DMA read/write operations. Only 32-bit registers for DMA addresses =/

I think Broadcom have the data book for download if you wish to double check...

**Comment by omstation** [comment] 2017-07-24 23:29
http://shop.dmp.com.tw/INT/products/25

I've found this card and was wondering if this could be a cheaper alternative to your current setup or possibly extend into the 64 bit territory. 

I haven't read the whole spec sheet but it seems like it should be able to do what you like and it is very inexpensive.

**Comment by ufrisk** [comment] 2017-07-25 06:16
Thanks, the 86Duino looks very interesting indeed. I'll have to check out the data sheet once back from defcon. I don't see much mentioning about 64-bit DMA in it though =/ so it might be that it's not capable. Are you able to find anything about it?

About the other board, I have the Spartan6 SP605 already, and that is the most likely FPGA dev card to be supported in the near future...

**Comment by omstation** [comment] 2017-07-25 07:00
Thanks for the info. I would love to see x64 dma using a spartan card. The issue I found with the galatea is that you have to manually purchase the ISE suite which I cannot imagine is cheap. I have seen that the SP605 does come with the software.

The Galatea is clearly more inexpensive that xilinx own card, but I would like to know how one could actually progam it without paying a fortune for software.

**Comment by omstation** [comment] 2017-07-25 21:29
Also, I've found this from BPlus, could this be used with modifications to do the same thing?

http://www.bplus.com.tw/adapter/PP2U.html

**Comment by omstation** [comment] 2017-07-26 00:49
Have you seen this board? http://www.latticesemi.com/Products/DevelopmentBoardsAndKits/ECP5VersaDevelopmentKit.aspx

Seems interesting and it is very cheap on their site but seems to be out of stock. They are sold in other places for a bit more though.

**Comment by ufrisk** [comment] 2017-07-26 20:27
Interesting, finding a capable board as cheap as $89 would be awesome, if not sold out ;) the other board is too close to the SP605 in the price. I just don't think it will be worthwhile for me to look into it.

**Comment by omstation** [comment] 2017-07-27 04:14
@ufrisk  

This might be an even better solution :

http://store.digilentinc.com/arty-artix-7-fpga-development-board-for-makers-and-hobbyists/

With the use of a simple PCIE extender, could be done for very cheap.

100$ usd. Also the fpga should have pcie compatibility.


In theory, this open source pcie core : 
https://github.com/enjoy-digital/litepcie
Could make the whole thing including software be basically 100$

**Comment by qmzero** [comment] 2017-08-02 12:04
Looks like the PP3380-AB card is literally out of stock everywhere. Is there any alternative to that? Regardless of price?

**Comment by ufrisk** [comment] 2017-08-02 12:17
oh, it must have sold out in the last few days.

No, there is no alternative for the PP3380-AB / USB3380-EVB at the moment.

The plan is to add support for more devices in the future. I'm afraid that you'll have to wait for them to restock or if you'll be able to purchase a used device from someone. If you check with them when they are going to restock please let us know here if you get a date.

**Comment by qmzero** [comment] 2017-08-02 12:20
Ah, ok, thank you for the quick reply ufrisk!

**Comment by omstation** [comment] 2017-08-06 01:00
@ufrisk I have been in contact with them and their distributors, M-Factors is out of stock, I got the last one. 

Also in the words of BPlus : "We don’t have plan to manufacture again recently."

**Comment by philipcs** [comment] 2017-08-13 03:13
I can confirm the above. 

Bplus stated "In fact, we don’t have plan to re-produce it currently.". MFactors stated "The PP2280-AB is currently unavailable and I’m afraid that it won't be around until the Factory gets an (MOQ of 100Pcs)." in the mail where they cancelled my order (I posted an order since it was still available according to their webpage around a week ago).

Do you have a timeframe for when software support for other hardware will be available?

**Comment by ufrisk** [comment] 2017-08-13 08:01
The plan is to add software support for the SP605 FPGA running [@d_olex](https://twitter.com/d_olex) bitstream, if/when he publishes it publicly. The SP605 is more bulky and more expensive though.

I know others are looking into possibly designing hardware as well, but I'm not aware of time frames, or if those projects will be completed.

So the short answer, no, I don't have a time frame unfortunately.

**Comment by Zibux** [comment] 2017-08-16 05:35
I started making my own project and run in to some problems.
I want to add pattern scanning for pcileech so i can find memory address.
Its hard to get my head around c because i usually work in c++.

So this is what i got.
I converted my c++ functions.
Converted
`BOOL inline DataCompare(const BYTE* pbData, const BYTE* pbMask, const char* pszMask)
{
	for (; *pszMask; ++pszMask, ++pbData, ++pbMask)
	{
		if (*pszMask == 'c' && *pbData != *pbMask)
		{
			return 0;
		}
	}
	return (*pszMask == NULL);
}

DWORD inline FindPattern(DWORD dwStart, DWORD dwSize, const BYTE* szSig, const char* szMask, _Inout_ PPCILEECH_CONTEXT ctx)
{
	PBYTE data = (PBYTE)malloc(dwSize);
	unsigned long bytesRead;
	if (!DeviceReadDMA(ctx, dwStart, data, dwSize, 0))
	{
		free(data);
		data = NULL;
		return NULL;
	}
	for (DWORD i = 0; i < dwSize; i++)
	{
		if (DataCompare((const BYTE*)(data + i), szSig, szMask))
		{
			free(data);
			data = NULL;
			return dwStart + i;
		}

	}
	free(data);
	data = NULL;
	return NULL;
}`
C++ version
`DWORD inline FindPattern(DWORD dwStart, DWORD dwSize, const BYTE* szSig, const char* szMask)
{
	PBYTE data = new BYTE[dwSize];
	unsigned long bytesRead;
	if (!ReadProcessMemory(process, (LPVOID)dwStart, data, dwSize, &bytesRead))
	{
		delete[] data;
		data = nullptr;

		return NULL;
	}
	for (DWORD i = 0; i < dwSize; i++)
	{
		if (DataCompare((const BYTE*)(data + i), szSig, szMask))
		{
			delete[] data;
			data = nullptr;
			return dwStart + i;
		}
	}
	delete[] data;
	data = nullptr;
	return NULL;
}`

Then i tried to read first 20 mb.
`	DWORD Start = 0;
	DWORD Size = 20000000;
	PBYTE data = (PBYTE)malloc(20000001);
	DeviceReadMEM(ctx, Start, data, Size, PCILEECH_MEM_FLAG_RETRYONFAIL);
	printf("Done");
	printbits(data);
	getchar();`
And got http://prntscr.com/g91iwv witch is not 20 mb.
Any help would be appreciated regarding reading memory and pattern scanning.

**Comment by ufrisk** [comment] 2017-08-16 06:47
Hi,

Can you please post questions/updates completely unrelated to the thread as a new issue?

- Have a look at the built in "search" or "patch" functionality in PCILeech.
- DeviceReadMem have size limitations. If reading unsupported large chunks of memory (such as 20MB) it will return FALSE upon failure. (you do not check for failures i code) Then try reading smaller chunks of memory. Typically the max supported size is 8 or 4MB depending on a few things, but it could be lower as well. An alternative would also be Util_Read16M which tries to read 16MB efficiently by detecting optimal max read size.

**Comment by erikJHO** [comment] 2017-09-05 08:50
Hello!
Sorry for the off-topic question. Could someone sell the PP3380-AB or USB3380-EVB? 
I'm ready to pay well. Write to erik.jhons@protonmail.com with any suggestions please.

**Comment by pimarplastics** [comment] 2017-09-05 16:09
Hi,
I apologize for trashing topic, but since all boards are sold out and I cannot get responce either from bplus and m-factor are sold out. 

Maybe someone know when boards will be avalible ?

Also same question as above I can pay well the PP3380-AB or USB3380-EVB, allegrowebster@gmail.com

**Comment by omstation** [comment] 2017-09-08 06:29
@erikJHO  @pimarplastics 

Emailed both of you guys. I only have one, selling because I'm designing this on an fpga now. 

First come first serve, whoever I can come with a deal first.


When I was in contact with m-factors/bplus, it seems they are not going to produce any more. Or atleast not for a while. I got the last one.

**Comment by erikJHO** [comment] 2017-09-08 09:25
Hello! How much money do you want?

**Comment by omstation** [comment] 2017-09-09 06:21
@erikJHO I emailed you back, lets keep the conversation out of the issue chat and to email.

**Comment by signal-5** [comment] 2017-09-09 09:08
@omstation Hope you have Telegram... I want to chat with you about new hardware. https://t.me[slash] joinchat[slash]Csc4MQzLB8Oi8X9s97nOdA
//Sigtrap

**Comment by eiselekd** [comment] 2018-03-04 19:05
Does anyone have a  USB3380-EVB? I would like to buy one.

**Comment by ufrisk** [comment] 2018-08-14 17:13
I believe the USB3380-EVB may be in stock again from the supplier.

**Closed by ufrisk** 2018-08-14 17:13 UTC
Labels: question
