### ISSUE TITLE
Error Message 0xf0000004

### ISSUE THREAD

**Issue by tbagmoney** [ufrisk/pcileech#4] opened 2016-08-31 02:39 UTC
Every time I try to do an action on a win10 or OSX client I receive the 0xf0000004 error. I have fiddled around with attempting to do a DMA on different operating systems but continue to get this error. I have had success with the first stage of inserting code into the kernel, but not past that point. Also after I insert code into the kernel, if I do it again it is sent to a different address in the memory, is that typical?

When I flashed the chip, I did not receive any confirmation from the linux terminal. Is that typical? It just sent me to the next command line without any output from the terminal. My gut is telling me that I may have not flashed the card correctly.

**Comment by ufrisk** [comment] 2016-08-31 06:24
- Flashing is most probably perfecly OK. If successful the kernel module won't type anything at all on the terminal - it will just load and show "SUCCESS" in dmsg.

- Also you are successful in inserting a kernel module into the OS kernel. It's perfecly normal that they end up at different physical memory addresses all the time.

- The 0xf0000004 error most likely indicate an error with the parameters you are supplying to the implant. ("#define STATUS_FAIL_INPPARAMS_BAD 0xf0000004" in ax64_common.h). Can you please send me the exact command you try to run which fail?

- I suspect you get another error message in Windows 10; unless you tried to load an OSX implant. OSX implants start with "ax64"; Windows implants start with "wx64".

**Comment by tbagmoney** [comment] 2016-09-01 04:08
![pcileech error](https://cloud.githubusercontent.com/assets/21096519/18155076/c51a0168-6fbe-11e6-98e5-73129bb84df5.png)

This is currently my issue.

**Comment by tbagmoney** [comment] 2016-09-01 04:19
I attempted it again and this is what I got:

![pcileech error2](https://cloud.githubusercontent.com/assets/21096519/18155231/8978b044-6fc0-11e6-9f5b-d1274798822d.png)

My results seem so inconsistent.

**Comment by ufrisk** [comment] 2016-09-01 08:38
Thanks,
I found a few issues with regards to error codes that I will fix in the next release.

I believe the root cause might be that the signature itself is missing though. I have to ask you to send me the file that is symlinked by: `/System/Library/Frameworks/OpenDirectory.framework/Versions/Current/Frameworks/CFOpenDirectory.framework/CFOpenDirectory`  together with your current OS X version number. The file should be around 450-500kB. Please email it to me at `pcileech@frizk.net`

In your last screenshot you didn't supply the "-0 1" hence the different error message.

**Comment by ufrisk** [comment] 2016-09-06 20:57
I really do need your version of CFOpenDirectory to be able to help and address this issue; alternatively if you resolved the issue please let me know. If I don't hear anything in a week I'll close this case.

**Comment by tbagmoney** [comment] 2016-09-12 23:54
I apologize for not responding to you sooner. I moved from one side of the world to another and was unable to get that file from the previous owner. I have tried it on new machines since then and have had success! Sorry to waste your time.

**Comment by ufrisk** [comment] 2016-09-13 07:57
Thank you for letting me know. I'll close the case.

Also, thank you for reporting this issue. I found errors in the memory reading algorithm that might had lead to failure to unlock the computer in rare circumstances that I fixed due to your report. Thanks =)

**Closed by ufrisk** 2016-09-13 07:57 UTC
