### ISSUE TITLE
FPGA: ERROR: Unable to connect to usb/ft601 device

### ISSUE THREAD

**Issue by FwRules** [ufrisk/pcileech#95] opened 2019-06-23 10:41 UTC
Hey,
i'm trying to follow the guide for this project.
I'm using AC701 board and the FT60x usb 3.0 convector. After i build a bit file and programmed the device (all seems about right) i tried running a few commands from the pcileech.exe and got the error about the FTDI FTD3XX.dll missing error. i have downloaded and added them and then the message changed to 
"FPGA: ERROR: Unable to connect to usb/ft601 device [0, v0.0, 0000]
PCILEECH: Failed to connect to the device"
i got this messages when running the  "pcileech.exe kmdload -kmd win10_x64 -device fpga -v" command i saw on another issue online.
how can i verify the connection to the board? (in order to verify the cable is fine or the converter)
i didn't saw anything regarding this error online so i'll be thankful for any advice or solutions :)
Thanks!!

**Comment by ufrisk** [comment] 2019-06-23 10:57
I'm going to assume you run the pcileech for Linux coz of the `./`. The FTD3XX.dll is required for Windows only.

For Linux you will need to download and build the driver from: https://github.com/enjoy-digital/pcie_screamer/tree/master/drivers/ft60x Also, you need to run as root or if you chmod the device that the driver exposes so it's read/write from your user. I have some instructions for Linux at: https://github.com/ufrisk/pcileech/wiki/PCILeech-on-Linux

the [0, v0.0 indicates you havne't connected to a successfully flashed FPGA device - this may be due to multiple reasons such as a driver problem, cable issue or incorrectly flashed device.  The 0000] indicates you have no or a bad PCIe connection (this is not the problem now since you haven't been able to connect to the device).

**Comment by FwRules** [comment] 2019-07-01 16:38
hi

I'm actually running it on windows (the './' was a mistake).

**Comment by JordanBoulan** [comment] 2019-07-21 22:34
I'm having the same issue, i get:

FPGA: ERROR: Unable to connect to usb/ft601 device [0, v0.0, 0000]
PCILEECH: Failed to connect to the device

flashed fine with openocd on linux. led works on button press. Windows 10 1709. On linux it just freezes and i get no output. Have dll on Windows and kernel module on linux. After about 7 hours i'm currently out of things to try.

**Comment by ufrisk** [comment] 2019-07-22 20:42
The error message indicates you are unable to connect over USB3 to the device. If you have it successfully flashed (VID=0x10ee / PID=0x0666 indicates that) I'm guessing it may be something with the usb connection or the driver.

Ensure the FT601 device is detected in device manager as shown below. It should have VID=0403/PID=601F most likely. Windows will want to download a kernel driver from windows update automatically at first connect. In addition to this you will have to have the .dll file (as you already do have).

If having the SP605/AC701 it may also be a good idea to re-attach the FT601 daughter card - sometimes there might be a bad connection. Also change USB port on your computer and try another cable.

![image](https://user-images.githubusercontent.com/18221464/61663832-c54fe280-acd1-11e9-9484-92d0119e09ce.png)

**Comment by JordanBoulan** [comment] 2019-07-25 01:03
I'm getting that exact same for the hids on the USB connection. The PCI connection is showing up as a Ethernet Controller in other devices with no driver (yellow exclamation point). I assumed that was fine but maybe not?

Also, I tested the USB cable with a hard drive that uses the same "double mini" type b connection and the hard drive seems to work fine.

Thanks for your help

**Comment by 3456668888** [comment] 2022-03-25 10:54
> 

Have you solved the error of [0, v0.00000]? I also encountered this problem. My device is screener m2

**Comment by ufrisk** [comment] 2022-03-27 17:22
@3456668888 please try run `pcileech.exe display -min 0x1000 -device fpga -v -vv` for additional debug output. Also make sure you have the `FTD3XX.dll` alongside pcileech.exe. Please let me know how it goes.

**Comment by 3456668888** [comment] 2022-03-28 06:53
> @3456888668686868请运行让我知道更多的`pcileech.exe display -min 0x1000 -device fpga -v -vv`调试情况。`FTD3XX.dll`
![D8K9{0` G6DPAQ8ZWB@XJFD](https://user-images.githubusercontent.com/59387456/160342322-c89fc7dc-9524-4db0-bad3-9b9c2d0ac5e4.png)

**Comment by 3456668888** [comment] 2022-03-28 06:57
> @3456668888 please try run `pcileech.exe display -min 0x1000 -device fpga -v -vv` for additional debug output. Also make sure you have the `FTD3XX.dll` alongside pcileech.exe. Please let me know how it goes.
![D8K9{0` G6DPAQ8ZWB@XJFD](https://user-images.githubusercontent.com/59387456/160342579-58f1b19f-4f6e-4570-9e3b-a9c46db1307b.png)

I use the screenerm2 device. It displays normally in my device manager, and its pcielink and fpgainit lights are always on

**Comment by ufrisk** [comment] 2022-04-03 18:50
Apologies for the late reply.

The most likely cause of this error is due to a bad flash of the FPGA. When powered on is the LED blinking a couple of times before it stops?

**Comment by 3456668888** [comment] 2022-04-04 02:04
> Apologies for the late reply.
> 
> The most likely cause of this error is due to a bad flash of the FPGA. When powered on is the LED blinking a couple of times before it stops?

After power on, PCIe link and FPGA init are always on, and usbdata flashes four times and then goes out
![image](https://user-images.githubusercontent.com/59387456/161462217-3c79842b-99d0-4f0c-85aa-77b51358b063.png)

**Comment by darknessbetz** [comment] 2022-08-02 13:44
Any new suggestions on this? Im getting this issue with my Squirrel.
Tried reflashing countless times, power cycling etc. etc.
USB data is flashing 3 times on startup while the 2 others are green constantly.

**Comment by 3456668888** [comment] 2022-08-02 13:47
> Any new suggestions on this? Im getting this issue with my Squirrel. Tried reflashing countless times, power cycling etc. etc. USB data is flashing 3 times on startup while the 2 others are green constantly.

I have replaced my DMA device. In my opinion, there is something wrong with the flash memory of the device.

**Comment by ufrisk** [comment] 2022-08-02 13:48
@darknessbetz what is your error message if you do:

`pcileech.exe display -min 0x1000 -v -device fpga`

also are you testing with the default firmware I have for download? If you're running a custom firmware please change to my default for testing.

if it's blinking 3 times or so at startup that means that the firmware is successfully loaded and configured onto the fpga.

**Comment by darknessbetz** [comment] 2022-08-02 14:25
Will be testing with your firmware once im home again. The odd thing about my case is that directly after boot it works flawless for 5-15 minutes, before losing connection and I have to reboot to get it working for the same amount of time again. I’ve tried it with a custom firmware, a confirmed working pool firmware and with the default squirrel firmware. Will be testing yours once im back home. This is the error im receiving after it has been working for 5-15 minutes. 
![5A7C3818-2F12-4211-B4DF-7327810B7EC3](https://user-images.githubusercontent.com/110474147/182398620-50770993-e985-46e0-b02c-1db4d882e594.png)

**Comment by ufrisk** [comment] 2022-08-02 14:39
@darknessbetz you're the 2nd person reporting it stops working after 20 minutes of use or so, the other guy was going to try to put a heat sink  on the FPGA and the USB chip. I can keep you updated how it goes.

**Comment by darknessbetz** [comment] 2022-08-02 14:57
I'm the same guy that contacted you on twitter regarding this issue. I wanted to also make a post on here just in case someone else had figured out / also have this issue. I'm getting a third USB cable today just to 100% exclude a cable issue.

**Comment by pschellack** [comment] 2022-08-16 09:22
@darknessbetz any new findings? I am having the same issue but with a little different error message:
DEVICE: FPGA: ERROR: Unable to retrieve required Device PCIe ID [4,v4.10,0000]

**Comment by darknessbetz** [comment] 2022-08-16 15:34
@pschellack Hey! Tried it with a third USB cable, same result. Tried it on 3 different computers with different motherboards, even AMD/Intel with same result. Pretty much my last option was a faulty board.
Requested a return from Lambda, no answer for almost 3 weeks now. So I went ahead and just bought a new one, and that one is working flawlessly. So it was in fact a faulty board. Still trying to get the first one returned. 
As of your issue I'm not so sure, I would suggest trying everything else before ordering a new one like I did!

Good luck with the troubleshooting, hope you find a cheaper solution than me! :D

**Comment by ArcticSlayy** [comment] 2023-05-16 13:02
Hello, I am also facing this issue but only when attempting this via the CLI. Whenever I have a python script using memprocfs library everything reads and works fine. Any tips?

**Comment by Fightergf** [comment] 2023-06-24 13:13
Hello ! I can’t deal with the board, the protection is disconnected, (IOMMU) is disconnected, tried through the laptop, the driver has been installed and has no errors, but he doesn’t see it, the system on the AMD, tried it on the intel, does not work, tried 1.3.0.2 - 1.3. 0.4 drivers, 4.4 - 4.15, I tried to connect the cable to the same computer where there is a fee, tried to kill the frequency of RAM (2800), put 2333MHz, nothing happened, I don’t want to flash the firmware. Device: FPGA: Error: Unable to Retrieve REQUIRED DEVICE PCIE ID [4, V4.11.0000]
As I understand it, there is a firmware here and he sees it, but they confuse it 0000, tried different slots Pcie x16/x4/x1
![12431531](https://github.com/ufrisk/pcileech/assets/46524515/852d2181-c0e7-43e5-b2c2-181a8d809c71)
![474734545](https://github.com/ufrisk/pcileech/assets/46524515/fc4c1d7f-2075-4b82-b31e-893029f019a4)
![56843234522222](https://github.com/ufrisk/pcileech/assets/46524515/14b83b8a-db1a-4a6f-9d2a-6f28110e9adb)
![53465788213](https://github.com/ufrisk/pcileech/assets/46524515/3928fd1a-5fc3-499c-a7d0-7c5cd27783d6)
plz Help me=(

**Comment by ufrisk** [comment] 2023-06-24 15:00
@Fightergf 

You have a working connection over USB.

You don't have a good PCIe connection to the target system for some reason, the 0000 tells that your device haven't been assigned a PCIe ID by the system for some reason.

Which device are you using and are you running the default PCILeech firmware I provide, or do you have a custom firmware?

If you have a custom firmware I'm sorry I cannot help. Sometimes custom firmwares are goofy. A lot of people are selling these but not so many contribute to my project. I'm not willing to give huge amounts of support for free just so that other people can earn a lot of money on my open source tools. If you're running custom firmware I'm afraid I'd have to ask you contact the vendor (or maybe someone else here have good ideas).

**Comment by Fightergf** [comment] 2023-06-24 15:09
thanks, I understand you, yes the firmware has already been installed, if I flash it myself, can I make it the same individual? Do you have a manual or instructions. It's a pity you don't have enough videos on Youtube =)

**Comment by Fightergf** [comment] 2023-06-25 20:09
PCI_E4 will be unavailable when an M.2 SSD is installed in the M2_2 slot.

**Comment by ufrisk** [comment] 2023-06-25 22:16
@Fightergf thanks for the update, by the sounds of it that sucks :\

**Comment by Fightergf** [comment] 2023-06-26 16:11
> @Fightergf thanks for the update, by the sounds of it that sucks :\
![667934353](https://github.com/ufrisk/pcileech/assets/46524515/1bee3f95-473c-46c7-a995-600bfb29878d)
This is fine?
 Pages read:     918016 / 4387712 (20%)
 Pages failed:   3469696 (79%)

**Comment by ufrisk** [comment] 2023-06-26 16:24
DMA is working :)

Probe is super agressive tho and things seems to have stopped working a short way in. This is quite normal and a reboot will clear it up.

If you're on AMD (also otherwise) I can recommend using the memmap feature for extra stability. https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt

Best wishes with your DMA attacking 👍 

Since your device works and issue is resolved I'm closing this issue.

**Closed by ufrisk** 2023-06-26 16:24 UTC
