### ISSUE TITLE
Device freezes

### ISSUE THREAD

**Issue by Frement** [ufrisk/pcileech#180] opened 2022-01-05 01:05 UTC
Something makes the whole device freeze. At some point when reading it will just completely freeze, which requires a reboot of the target PC.

```
Intel i7-4790K
Screamer M.2
Windows 10 x64
```

```
DEVICE: FPGA: ERROR: Unable to connect to USB/FT601 device [0,v0.0,0000]
PCILEECH: Failed to connect to the device.
```

After rebooting the target PC it will then sometimes fail to read anything. So N number of reboots will fix the issue, but that really isn't a solution.

This is now with the newest version of everything. Let me know if I can provide additional information that would be helpful.

**Comment by ufrisk** [comment] 2022-01-05 20:42
I'm sorry, I don't really have a good idea what's going on here. It looks like you may have issues connecting to the device over USB somehow. You could try changing USB port (probably won't work, but worth a try).

Also, shutdown+startup is probably better than reboot for clearing any errors.

It's really hard for me to know whats going on here. I don't have access to a system in which I'm able to replicate this issue. I haven't seen it before. Maybe it's a bit similar like this one: https://github.com/ufrisk/pcileech-fpga/issues/93  (but that issue wouldn't freeze the USB - just the PCIe). Also I suspect you don't have a 2nd device to test with in case there is a hardware issue? (doesn't look like one).

**Comment by Frement** [comment] 2022-01-06 07:55
By rebooting I meant a full shutdown and then powering the system on again. Once the device lockup happens, a reboot then fixes the USB connection, but device still fails to read any memory. A second reboot will allow the device to read memory properly again.

Any suggestions on what I could do to help debug this? So far I haven't come up with a way to reproduce this programmatically.

**Comment by ufrisk** [comment] 2022-01-06 14:24
You can try a few different things I guess, but these issue are really hard to find and not many have reported issues around this, and when they do it's usually something with the usb connection and it will always fail (not fail after a while), anyway:

1) try connecting multiple times. like 2-3 times to see if the blockage clears. Also connect with `pcileech.exe display -min 0x1000 -device fpga://devreload=1

2) always supply a memory map as per: https://github.com/ufrisk/LeechCore/wiki/Device_FPGA_AMD_Thunderbolt and avoid using the "probe" command.

3) if the issue is related to: https://github.com/ufrisk/pcileech-fpga/issues/93 please change this line: https://github.com/ufrisk/pcileech-fpga/blob/23952f78ff5975787083d642bae8d00d39a74ad4/ScreamerM2/src/pcileech_pcie_a7.sv#L135 to `.m_axis_rx_tready           ( 1'b1  ),  // <-` and rebuild and re-flash the device. After the change you may have to specify fpga option readsize, i.e. `pcileech.exe display -min 0x1000 -device fpga://readsize=0x10000`

4) if the issue is occurring after a long time of use maybe it's a overheat issue? It could be a hardware issue as well, but it's a strange one if it is...

**Comment by Frement** [comment] 2022-01-10 06:50
I did #1, #2, #3 and also changed the USB port to another one again, I had it running for a full 24 hours without any issues. I'm guessing #1 is irrelevant since it hasn't gotten blocked, but that functionality is there as a safe guard to see if that will fix it if it happens again.

If you'll keep this open for this week I can provide a final verdict, I'll test which change breaks it again.

Thanks so much for the help.

**Comment by ufrisk** [comment] 2022-03-31 14:51
I'm closing this issue since it seems to be resolved now. Best wishes with your DMA attacking.

**Closed by ufrisk** 2022-03-31 14:51 UTC
