### ISSUE TITLE
randomly disconnecting

### ISSUE THREAD

**Issue by unknownpk** [ufrisk/pcileech#146] opened 2020-08-14 19:41 UTC
could you explain or tell me why im randomly disconnecting from PCILeech AKA reading memory it will be fine to connect etc but when reading / writing it randomly disconnects and results are NULL and i have to reconnect to the device? is there a max amount of times to read / write? i know limit is 500mb but im no where near that or am i missing something? thanks!

ps. with 4.5 when and if it disconnects now i have to restart the pc to allow it to connect really annoying :(

**Comment by ufrisk** [comment] 2020-08-15 12:41
Thank you for reporting.

I've noticed sporadic disconnects as well which I'm trying to pinpoint. For me, they usually recover by themselves though and there is no need to disconnect; even though a read may take a lot of extra time whenever this happens.

There is no 500MB limit though. And there are no limit on read/write. But this problem happens when the device is really active. I'm currently looking into it. But it may take some time.

**Comment by unknownpk** [comment] 2020-08-15 14:14
hmmm when i leave my app open it just keeps returning NULL always only way to fix is to reopen it do you know if this happen with 4.4? or is this issue only with 4.5 because if its an issue with only 4.5 ill just down grade till you fix :)

**Comment by xNarkon** [comment] 2020-10-22 10:26
@ufrisk any update? :D

**Comment by ufrisk** [comment] 2020-10-22 22:30
unfortunately not, I put quit a lot of time into this a month ago; I even recoded the ft601 handling logic from scratch but with no change. Right now I'm just out of ideas why this may be happening. I tried changing a lot of things all with zero effect.

**Comment by xNarkon** [comment] 2020-10-23 05:36
It's sad, but thanks a lot! 

I've got one idea. Maybe the problem is in the Xilinx core. I have noticed that it mostly happen when FPGA was at stress for a quite long time. The FPGA board is very hot when this problem occurs, so maybe this is the case? Temperature?

**Comment by ufrisk** [comment] 2020-10-24 22:34
Thanks for the suggestion; the FT601 is super hot as well so it may very well be that it's that component getting too hot as well. It's definitely a thing I will have to try out. I'll order some heat spreaders and test. Lets hope it's the issue.

**Comment by ufrisk** [comment] 2024-06-01 15:51
I'm closing this issue due to old age.

**Closed by ufrisk** 2024-06-01 15:51 UTC
Labels: bug
